import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
      backgroundImage: {
        'clear-day': "url('/background-images/sunny-background.webp')",
        'snow': "url('/background-images/snow-background.webp')",
        'rain': "url('/background-images/moderate-rain-background.webp')",
        'cloudy': "url('/background-images/cloudy-background.webp')",
        'fog': "url('/background-images/foggy-background.webp')",
        'thunderstorm': "url('/background-images/thunderstorm-background.webp')",
        'light-rain': "url('/background-images/light-rain-background.webp')",
        'clear-night': "url('/background-images/clear-night-background.webp')",
        'partly-cloudy-day': "url('/background-images/partly-cloudy-background.webp')",
        'partly-cloudy-night': "url('/background-images/partly-cloudy-night-background.webp')",
        'home': "",
        'pressure-very-low': "url('/icons/pressure-very-low.svg')",
        'pressure-low': "url('/icons/pressure-low.svg')",
        'pressure-normal': "url('/icons/pressure-normal.svg')",
        'pressure-high': "url('/icons/pressure-high.svg')",
        'pressure-very-high': "url('/icons/pressure-very-high.svg')",
        'humidity-very-low': "url('/icons/humidity-very-low.svg')",
        'humidity-low': "url('/icons/humidity-low.svg')",
        'humidity-moderate': "url('/icons/humidity-moderate.svg')",
        'humidity-high': "url('/icons/humidity-high.svg')",
        'humidity-very-high': "url('/icons/humidity-very-high.svg')",
        'air-quality-very-poor': "url('/icons/air-quality-very-poor.svg')",
        'air-quality-poor': "url('/icons/air-quality-poor.svg')",
        'air-quality-moderate': "url('/icons/air-quality-moderate.svg')",
        'air-quality-fair': "url('/icons/air-quality-fair.svg')",
        'air-quality-good': "url('/icons/air-quality-good.svg')",
        'uv-index-low': "url('/icons/uv-index-low.svg')",
        'uv-index-moderate': "url('/icons/uv-index-moderate.svg')",
        'uv-index-high': "url('/icons/uv-index-high.svg')",
        'uv-index-very-high': "url('/icons/uv-index-very-high.svg')",
        'uv-index-extreme': "url('/icons/uv-index-extreme.svg')",
        'sunrise-0': "url('/icons/sunrise-0.svg')",
        'sunrise-1': "url('/icons/sunrise-1.svg')",
        'sunrise-2': "url('/icons/sunrise-2.svg')",
        'sunrise-3': "url('/icons/sunrise-3.svg')",
        'sunrise-4': "url('/icons/sunrise-4.svg')",
        'sunrise-5': "url('/icons/sunrise-5.svg')",
        'sunrise-6': "url('/icons/sunrise-6.svg')",
        'sunrise-7': "url('/icons/sunrise-7.svg')",
        'sunrise-8': "url('/icons/sunrise-8.svg')",
        'sunrise-9': "url('/icons/sunrise-9.svg')",
        'sunrise-10': "url('/icons/sunrise-10.svg')",
        'sunrise-11': "url('/icons/sunrise-11.svg')",
        'sunrise-12': "url('/icons/sunrise-12.svg')",
        'sunrise-13': "url('/icons/sunrise-13.svg')",
        'sunrise-14': "url('/icons/sunrise-14.svg')",
        'sunrise-15': "url('/icons/sunrise-15.svg')",
      },
    },
  },
  plugins: [],
} satisfies Config;
