/**
 * Root layout — wraps every route in the app.
 *
 * This is a SERVER COMPONENT (note there is no 'use client' directive): it runs
 * only on the server, and none of its code is shipped to the browser. That is
 * the App Router default, and it is fine here because the document shell needs
 * no interactivity.
 *
 * `children` is whatever page matched the URL — for this app, always page.tsx.
 * A layout persists across navigation, so state inside it would survive a route
 * change (this one holds none).
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// next/font downloads the font at build time and self-hosts it, so there is no
// runtime request to Google and no flash of unstyled text. Each call returns a
// CSS variable name we attach to <body> below.
// NOTE: globals.css currently sets `font-family: Arial...` on body, which
// overrides these. Fix one or the other when you get a chance.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Exporting `metadata` from a layout or page is how the App Router sets <head>
// tags. Next renders the <title> and <meta> for you.
export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
